name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install Node.js dependencies
        run: npm install --force

      - name: Build the React application
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: firebase use --token "$FIREBASE_TOKEN" --add "$FIREBASE_PROJECT_ID"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: bizcard-web

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}